name: Deploy to Heroku

on:
  push:
    branches:
      - master
      
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: pokedexqt-heroku-rest-api
            heroku_email: ville.niemenmaa@gmail.com
            healthcheck: https://pokedexqt-heroku-rest-api.herokuapp.com/health
            checkstring: ok